### ISSUE TITLE
Issues & suggestions

### ISSUE THREAD

**Issue by VasilisKos** [Caleb-Seely/Garmin-Remote-Camera#1]
After managing to get access to the companion app...:
1. On the Descent G1, and probably all the Instinct series (which have the same screen layout as Descent), the little circular button icon on the top right corner of the watch screen is not properly centered in the circular little window on the to right corner of the screen. Needs to be aligned, and probably the word "REC" should be aligned too, to be visible when recording video.
2. Please add resolution and aspect ratio option in the Android app (now it's only 8MP and 4:3 photos, and 4:3 videos).
3. Fix the preview in Android app. It now covers the whole phone screen, though photos are taken in 4:3 ratio, thus you can't properly frame the photos. 
4. The countdown numbers are cut out in landscape mode in the Android screen. They should either be smaller or centered properly. 

Nice job! Keep improving it!

**Comment by Caleb-Seely** [comment]
1) The issue with the off-center button on Descent and Instinct series has been fixed. The circular icon is now properly aligned in sub-screen layouts, and the "REC" label should now display correctly during video recording.

2) The Android app now includes a Settings menu where you can choose between 4:3 and 16:9 aspect ratios. Resolution selection has also been improved to better match the highest available quality on the back camera.

3) The preview screen now properly reflects your selected aspect ratio, so framing your shots should be much easier and more accurate.

4) Countdown numbers in landscape mode have been resized and repositioned so they no longer get cut off.


Thanks again for taking the time to give feedback!

**Comment by VasilisKos** [comment]
Thanks a lot. But the apk hasn't been updated in download link.

**Comment by Caleb-Seely** [comment]
You're right, I just added the updated apk. Download link should be working now.

**Comment by VasilisKos** [comment]
The watch app has been improved, and it's quite perfect. The only thing is that the app icon should be a little bit smaller to fit properly in the circular window of Descent and Instinct series. 
The Android app:
1. Has a major bug. Horizontally captured videos are always saved as vertical. This should be fixed.
2. It still doesn't support fully the phone's camera resolution. It only captures 8 MP photos on my 16 MP Nokia X20 phone. 
3. The app should keep the phone screen active, like all camera apps do.
4. Please make the app icon adaptive.
5. Also, I think it's about time you should upload the Android app on Google Play.
Keep up the good work! 😉
